name: Java CI with Maven - Test and package
on: [pull_request] 
jobs:
 job1:
  name: job1
  runs-on: ubuntu-latest 
  steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setupJava
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
        cache: 'maven'
    - name: cache maven
      uses: actions/cache@V4
      with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
    - name: buildPackage
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')