name: Java CI with Maven - Test and package
on: [pull_request] 
jobs:
 job1:
  name: job1
  runs-on: ubuntu-latest 
  steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: setupJava with cache maven
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
        cache: 'maven'
    - name: Cache SonarQube
      uses: actions/cache@v4
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar
    - name: buildPackage
      env: 
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')